[container.image]
repository="anuruddhal" # Container repository to host the container
name="hello-api" # Name of the container image
tag="sample12" # Tag of the container

[[cloud.secret.files]]
file="./data/data.txt" # Path to the secret file
mount_dir="./data" # Path of the file within the container

[[cloud.config.secrets]]
file="./data/Config.toml" # Path to the secret Config.toml
