[container.image]
name = "build-arg"
repository = "xlight05"
tag = "1.0.0"

[settings]
buildImage = false

[graalvm.builder]
base = "ballerina/musl-native-builder:2201.7.x"
buildCmd = "sh build-native.sh custom_builder.jar custom_builder '--static --libc=musl'"
